config/routes.rb
Rails.application.routes.draw do

  devise_for :users
  root to: "infomations#index"

  resources :users, only: [:show]

  resources :infomations, only: [:index,:create,:destroy] do
    collection do
     get 'fresh'
     get 'tool'
    end
  end

  resources :contacts, only: [:new,:create,:show,:index] do
    collection do
      get 'success'
     end
   end

  resources :articles do
    resources :comments, only: [:create,:destroy]

    collection do
      get 'success'
      get 'success2'
      get 'search'
      get 'all'
     end
   end


   resources :characters, only: [:index] do
    collection do
      get 'n0100'
      get 'n0200'
      get 'n0300'
      get 'character'
      
     end
   end


end

app/models/article.rb
class Article < ApplicationRecord
  belongs_to :user
  has_many :comments, dependent: :destroy
  is_impressionable counter_cache: true

  def self.search(search)
    if search != ''
      Article.where('first_pokemon LIKE(?)', "%#{search}%")
             .or Article.where('second_pokemon LIKE(?)', "%#{search}%")
                        .or Article.where('third_pokemon LIKE(?)', "%#{search}%")
                                   .or Article.where('force_pokemon LIKE(?)', "%#{search}%")
                                              .or Article.where('fifth_pokemon LIKE(?)', "%#{search}%")
                                                         .or Article.where('sixth_pokemon LIKE(?)', "%#{search}%")
    else
      Article.all.order(created_at: 'DESC').limit(20)
    end
  end

  with_options presence: true do
    validates :title,
              :first_pokemon_hp,
              :first_pokemon_attack, :first_pokemon_defence, :first_pokemon_spattack, :first_pokemon_spdefence, :first_pokemon_speed,
              :second_pokemon_hp,
              :second_pokemon_attack, :second_pokemon_defence, :second_pokemon_spattack, :second_pokemon_spdefence, :second_pokemon_speed,
              :third_pokemon_hp,
              :third_pokemon_attack, :third_pokemon_defence, :third_pokemon_spattack, :third_pokemon_spdefence, :third_pokemon_speed,
              :force_pokemon_hp,
              :force_pokemon_attack, :force_pokemon_defence, :force_pokemon_spattack, :force_pokemon_spdefence, :force_pokemon_speed,
              :fifth_pokemon_hp,
              :fifth_pokemon_attack, :fifth_pokemon_defence, :fifth_pokemon_spattack, :fifth_pokemon_spdefence, :fifth_pokemon_speed,
              :sixth_pokemon_hp,
              :sixth_pokemon_attack, :sixth_pokemon_defence, :sixth_pokemon_spattack, :sixth_pokemon_spdefence, :sixth_pokemon_speed,
              :article_text,

   
                :first_pokemon, :first_pokemon_special, :first_pokemon_item, :first_pokemon_temper_id,
                :first_pokemon_first_weapon, :first_pokemon_second_weapon, :first_pokemon_third_weapon, :first_pokemon_force_weapon,
                :second_pokemon, :second_pokemon_special, :second_pokemon_item, :second_pokemon_temper_id,
                :second_pokemon_first_weapon, :second_pokemon_second_weapon, :second_pokemon_third_weapon, :second_pokemon_force_weapon,
                :third_pokemon, :third_pokemon_special, :third_pokemon_item, :third_pokemon_temper_id,
                :third_pokemon_first_weapon, :third_pokemon_second_weapon, :third_pokemon_third_weapon, :third_pokemon_force_weapon,
                :force_pokemon, :force_pokemon_special, :force_pokemon_item, :force_pokemon_temper_id,
                :force_pokemon_first_weapon, :force_pokemon_second_weapon, :force_pokemon_third_weapon, :force_pokemon_force_weapon,
                :fifth_pokemon, :fifth_pokemon_special, :fifth_pokemon_item, :fifth_pokemon_temper_id,
                :fifth_pokemon_first_weapon, :fifth_pokemon_second_weapon, :fifth_pokemon_third_weapon, :fifth_pokemon_force_weapon,
                :sixth_pokemon, :sixth_pokemon_special, :sixth_pokemon_item, :sixth_pokemon_temper_id,
                :sixth_pokemon_first_weapon, :sixth_pokemon_second_weapon, :sixth_pokemon_third_weapon, :sixth_pokemon_force_weapon
  end
end

app/controllers/articles_controller.rb
class ArticlesController < ApplicationController
  before_action :authenticate_user!, only: [:new, :edit]
  before_action :article_find, only: [:update, :show, :edit,:destroy]

  def index
    @articles = Article.all.order(created_at: 'DESC').limit(20)
    @rank = Article.order(impressions_count: 'DESC',created_at: 'DESC').limit(5)

    @pokerank1 = @rank.sample
    @pokerank2 = @rank.sample
    @pokerank3 = @rank.sample
    @pokerank4 = @rank.sample
    @pokerank5 = @rank.sample
    @pokerank6 = @rank.sample
  end

  def new
    @article = Article.new
  end

  def create
    @article = Article.new(article_params)
    if @article.save
      redirect_to success_articles_path
    else
      render :new
    end
  end

  def edit
  end

  def update
    if @article.update(article_params)
      redirect_to article_path(@article.id)
    else
      render :edit
    end
  end

  def destroy
    if @article.destroy
      redirect_to success2_articles_path
    end
  end

  def success
  end

  def success2
  end

  def search
    @articles = Article.search(params[:keyword]).order(created_at: 'DESC').page(params[:page]).per(10)
  end

  def show
    @comment = Comment.new
    @comments = @article.comments.all
    impressionist(@article, nil, unique: [:ip_address])
  end

  def all
    @articles = Article.all.order(created_at: 'DESC').page(params[:page]).per(10)
  end

  private

  def article_find
    @article = Article.find(params[:id])
  end

  def article_params
    params.require(:article).permit(:title,
                                    :first_pokemon, :first_pokemon_special, :first_pokemon_item, :first_pokemon_temper_id, :first_pokemon_hp,
                                    :first_pokemon_attack, :first_pokemon_defence, :first_pokemon_spattack, :first_pokemon_spdefence, :first_pokemon_speed,
                                    :first_pokemon_first_weapon, :first_pokemon_second_weapon, :first_pokemon_third_weapon, :first_pokemon_force_weapon,
                                    :second_pokemon, :second_pokemon_special, :second_pokemon_item, :second_pokemon_temper_id, :second_pokemon_hp,
                                    :second_pokemon_attack, :second_pokemon_defence, :second_pokemon_spattack, :second_pokemon_spdefence, :second_pokemon_speed,
                                    :second_pokemon_first_weapon, :second_pokemon_second_weapon, :second_pokemon_third_weapon, :second_pokemon_force_weapon,
                                    :third_pokemon, :third_pokemon_special, :third_pokemon_item, :third_pokemon_temper_id, :third_pokemon_hp,
                                    :third_pokemon_attack, :third_pokemon_defence, :third_pokemon_spattack, :third_pokemon_spdefence, :third_pokemon_speed,
                                    :third_pokemon_first_weapon, :third_pokemon_second_weapon, :third_pokemon_third_weapon, :third_pokemon_force_weapon,
                                    :force_pokemon, :force_pokemon_special, :force_pokemon_item, :force_pokemon_temper_id, :force_pokemon_hp,
                                    :force_pokemon_attack, :force_pokemon_defence, :force_pokemon_spattack, :force_pokemon_spdefence, :force_pokemon_speed,
                                    :force_pokemon_first_weapon, :force_pokemon_second_weapon, :force_pokemon_third_weapon, :force_pokemon_force_weapon,
                                    :fifth_pokemon, :fifth_pokemon_special, :fifth_pokemon_item, :fifth_pokemon_temper_id, :fifth_pokemon_hp,
                                    :fifth_pokemon_attack, :fifth_pokemon_defence, :fifth_pokemon_spattack, :fifth_pokemon_spdefence, :fifth_pokemon_speed,
                                    :fifth_pokemon_first_weapon, :fifth_pokemon_second_weapon, :fifth_pokemon_third_weapon, :fifth_pokemon_force_weapon,
                                    :sixth_pokemon, :sixth_pokemon_special, :sixth_pokemon_item, :sixth_pokemon_temper_id, :sixth_pokemon_hp,
                                    :sixth_pokemon_attack, :sixth_pokemon_defence, :sixth_pokemon_spattack, :sixth_pokemon_spdefence, :sixth_pokemon_speed,
                                    :sixth_pokemon_first_weapon, :sixth_pokemon_second_weapon, :sixth_pokemon_third_weapon, :sixth_pokemon_force_weapon,
                                    :article_text).merge(user_id: current_user.id)
  end
end

app/helpers/articles_helper.rb
module ArticlesHelper
end

app/views/articles/_show01.html.erb
<div class="show-monster-alone">

        <div class="show-monster-top">
        <%= render partial: "monster001", locals: { article: @article } %>
        <div class="show-pokemon-name"><%= @article.first_pokemon %></div>
        </div>

        <div class="show-monster-center">
          <div class="show-monster-text">特性：<%= @article.first_pokemon_special %></div>
          <div class="show-monster-text">持ち物：<%= @article.first_pokemon_item %></div>
          <div class="show-monster-text">性格：<%= @article.first_pokemon_temper_id %></div>
          <div class="show-monster-text">
          <%= @article.first_pokemon_hp %>-<%= @article.first_pokemon_attack %>-<%= @article.first_pokemon_defence %>-
          <%= @article.first_pokemon_spattack %>-<%= @article.first_pokemon_spdefence %>-<%= @article.first_pokemon_speed %>
        </div>

          <div class="show-weapon-area">
            <div>
              <span class="show-monster-weapon"><%= @article.first_pokemon_first_weapon %></span>
              <span class="show-monster-weapon"><%= @article.first_pokemon_second_weapon %></span>
            </div>
          </div>  

          <div class="show-weapon-area">
            <span class="show-monster-weapon"><%= @article.first_pokemon_third_weapon %></span>
            <span class="show-monster-weapon"><%= @article.first_pokemon_force_weapon %></span>
            </div>
          </div>

        

      </div >

app/views/articles/_show05.html.erb
 <div class="show-monster-alone">

        <div class="show-monster-top">
          <%= render partial: "monster005", locals: { article: @article } %>
          <div class="show-pokemon-name"><%= @article.fifth_pokemon %></div>
        </div>

        <div class="show-monster-center">
          <div class="show-monster-text">特性：<%= @article.fifth_pokemon_special %></div>
          <div class="show-monster-text">持ち物：<%= @article.fifth_pokemon_item %></div>
          <div class="show-monster-text">性格：<%= @article.fifth_pokemon_temper_id %></div>
          <div class="show-monster-text">
          <%= @article.fifth_pokemon_hp %>-<%= @article.fifth_pokemon_attack %>-<%= @article.fifth_pokemon_defence %>-
          <%= @article.fifth_pokemon_spattack %>-<%= @article.fifth_pokemon_spdefence %>-<%= @article.fifth_pokemon_speed %>
        </div>

        <div class="show-weapon-area">
          <div>
            <span class="show-monster-weapon"><%= @article.fifth_pokemon_first_weapon %></span>
            <span class="show-monster-weapon"><%= @article.fifth_pokemon_second_weapon %></span>
          </div>
        </div>  

        <div class="show-weapon-area">
          <div>
            <span class="show-monster-weapon"><%= @article.fifth_pokemon_third_weapon %></span>
            <span class="show-monster-weapon"><%= @article.fifth_pokemon_force_weapon %></span>
          </div>  
        </div>        
    </div>  
    </div>

app/views/articles/index.html.erb
<%= render "layouts/header"%>


<div class="w-btn">

  <div class="article-index">
    <div class="action-button">
      <%=link_to '構築を投稿する', new_article_path,class: 'action-btn' %>
    </div>
    <div class="action-button">
       <%=link_to '構築を検索する', search_articles_path,class: 'action-btn' %>
    </div>
  </div>
    
</div>

  <div class="article-second">
  
    <div class="ranking">
    <h1 class="blue-title">ー注目のポケモンー</h1>

  <%if @pokerank1.present? %>
      <%#----------------------------------------------------------------%>
      <div class="ranking-field">

        <div class="rank-mon">
        <div class="ranking-text"><%=@pokerank1.first_pokemon %></div>
        <%= render partial: "01indexmonseter", locals: { article: @pokerank1 } %>
        </div>

        <div class="ranking-small">
          <p class="ranking-small-text">
          <%=@pokerank1.first_pokemon_special %>/
          <%=@pokerank1.first_pokemon_item %>/
          <%=@pokerank1.first_pokemon_temper_id %></p><br>

          <p class="ranking-small-text">
          <%=@pokerank1.first_pokemon_hp %>-
          <%=@pokerank1.first_pokemon_attack %>-
          <%=@pokerank1.first_pokemon_defence %>-
          <%=@pokerank1.first_pokemon_spattack %>-
          <%=@pokerank1.first_pokemon_spdefence %>-
          <%=@pokerank1.first_pokemon_speed %></p><br>
          
          <p class="ranking-small-text">
          <%=@pokerank1.first_pokemon_first_weapon %>/
          <%=@pokerank1.first_pokemon_second_weapon %>/
          <%=@pokerank1.first_pokemon_third_weapon %>/
          <%=@pokerank1.first_pokemon_force_weapon %>
          </p><br>

          <%=link_to "このポケモンの記事を見にいく", article_path(@pokerank1.id), class:'small-link' %>


        </div>




      </div>
      <%#----------------------------------------------------------------%>

      <%#----------------------------------------------------------------%>

      <div class="ranking-field">

        <div class="rank-mon">
        <div class="ranking-text"><%=@pokerank2.force_pokemon %></div>
        <%= render partial: "04indexmonster", locals: { article: @pokerank2 } %>
        </div>

        <div class="ranking-small">
          <p class="ranking-small-text">
          <%=@pokerank2.force_pokemon_special %>/
          <%=@pokerank2.force_pokemon_item %>/
          <%=@pokerank2.force_pokemon_temper_id %></p><br>

          <p class="ranking-small-text">
          <%=@pokerank2.force_pokemon_hp %>-
          <%=@pokerank2.force_pokemon_attack %>-
          <%=@pokerank2.force_pokemon_defence %>-
          <%=@pokerank2.force_pokemon_spattack %>-
          <%=@pokerank2.force_pokemon_spdefence %>-
          <%=@pokerank2.force_pokemon_speed %></p><br>
          
          <p class="ranking-small-text">
          <%=@pokerank2.force_pokemon_first_weapon %>/
          <%=@pokerank2.force_pokemon_second_weapon %>/
          <%=@pokerank2.force_pokemon_third_weapon %>/
          <%=@pokerank2.force_pokemon_force_weapon %>
          </p><br>

          <%=link_to "このポケモンの記事を見にいく", article_path(@pokerank2.id), class:'small-link' %>


        </div>

      </div>


      <div class="ranking-field">
      
        <div class="rank-mon">
        <div class="ranking-text"><%=@pokerank3.second_pokemon %></div>
        <%= render partial: "02indexmonster", locals: { article: @pokerank3 } %>
        </div>

        <div class="ranking-small">
          <p class="ranking-small-text">
          <%=@pokerank3.second_pokemon_special %>/
          <%=@pokerank3.second_pokemon_item %>/
          <%=@pokerank3.second_pokemon_temper_id %></p><br>

          <p class="ranking-small-text">
          <%=@pokerank3.second_pokemon_hp %>-
          <%=@pokerank3.second_pokemon_attack %>-
          <%=@pokerank3.second_pokemon_defence %>-
          <%=@pokerank3.second_pokemon_spattack %>-
          <%=@pokerank3.second_pokemon_spdefence %>-
          <%=@pokerank3.second_pokemon_speed %></p><br>
          
          <p class="ranking-small-text">
          <%=@pokerank3.second_pokemon_first_weapon %>/
          <%=@pokerank3.second_pokemon_second_weapon %>/
          <%=@pokerank3.second_pokemon_third_weapon %>/
          <%=@pokerank3.second_pokemon_force_weapon %>
          </p><br>

          <%=link_to "このポケモンの記事を見にいく", article_path(@pokerank3.id), class:'small-link' %>


        </div>

      </div>

      <%#----------------------------------------------------------------%>

      <%#----------------------------------------------------------------%>

      <div class="ranking-field">

        <div class="rank-mon">
        <div class="ranking-text"><%=@pokerank4.sixth_pokemon %></div>
        <%= render partial: "06indexmonster", locals: { article: @pokerank4 } %>
        </div>

        <div class="ranking-small">
          <p class="ranking-small-text">
          <%=@pokerank4.sixth_pokemon_special %>/
          <%=@pokerank4.sixth_pokemon_item %>/
          <%=@pokerank4.sixth_pokemon_temper_id %></p><br>

          <p class="ranking-small-text">
          <%=@pokerank4.sixth_pokemon_hp %>-
          <%=@pokerank4.sixth_pokemon_attack %>-
          <%=@pokerank4.sixth_pokemon_defence %>-
          <%=@pokerank4.sixth_pokemon_spattack %>-
          <%=@pokerank4.sixth_pokemon_spdefence %>-
          <%=@pokerank4.sixth_pokemon_speed %></p><br>
          
          <p class="ranking-small-text">
          <%=@pokerank4.sixth_pokemon_first_weapon %>/
          <%=@pokerank4.sixth_pokemon_second_weapon %>/
          <%=@pokerank4.sixth_pokemon_third_weapon %>/
          <%=@pokerank4.sixth_pokemon_force_weapon %>
          </p><br>

          <%=link_to "このポケモンの記事を見にいく", article_path(@pokerank4.id), class:'small-link' %>


        </div>

      
      </div>

       <%#----------------------------------------------------------------%>

      <div class="ranking-field">

      <div class="rank-mon">
        <div class="ranking-text"><%=@pokerank5.fifth_pokemon %></div>
        <%= render partial: "05indexmonster", locals: { article: @pokerank5 } %>
        </div>

      <div class="ranking-small">
          <p class="ranking-small-text">
          <%=@pokerank5.fifth_pokemon_special %>/
          <%=@pokerank5.fifth_pokemon_item %>/
          <%=@pokerank5.fifth_pokemon_temper_id %></p><br>

          <p class="ranking-small-text">
          <%=@pokerank5.fifth_pokemon_hp %>-
          <%=@pokerank5.fifth_pokemon_attack %>-
          <%=@pokerank5.fifth_pokemon_defence %>-
          <%=@pokerank5.fifth_pokemon_spattack %>-
          <%=@pokerank5.fifth_pokemon_spdefence %>-
          <%=@pokerank5.fifth_pokemon_speed %></p><br>
          
          <p class="ranking-small-text">
          <%=@pokerank5.fifth_pokemon_first_weapon %>/
          <%=@pokerank5.fifth_pokemon_second_weapon %>/
          <%=@pokerank5.fifth_pokemon_third_weapon %>/
          <%=@pokerank5.fifth_pokemon_force_weapon %>
          </p><br>

          <%=link_to "このポケモンの記事を見にいく", article_path(@pokerank5.id), class:'small-link' %>


        </div>
      
      </div>

     
 
      <%#----------------------------------------------------------------%>

      <div class="ranking-field">
      
      <div class="rank-mon">
        <div class="ranking-text"><%=@pokerank6.third_pokemon %></div>
        <%= render partial: "03indexmonster", locals: { article: @pokerank6 } %>
        </div>

      <div class="ranking-small">
          <p class="ranking-small-text">
          <%=@pokerank6.third_pokemon_special %>/
          <%=@pokerank6.third_pokemon_item %>/
          <%=@pokerank6.third_pokemon_temper_id %></p><br>

          <p class="ranking-small-text">
          <%=@pokerank6.third_pokemon_hp %>-
          <%=@pokerank6.third_pokemon_attack %>-
          <%=@pokerank6.third_pokemon_defence %>-
          <%=@pokerank6.third_pokemon_spattack %>-
          <%=@pokerank6.third_pokemon_spdefence %>-
          <%=@pokerank6.third_pokemon_speed %></p><br>
          
          <p class="ranking-small-text">
          <%=@pokerank6.third_pokemon_first_weapon %>/
          <%=@pokerank6.third_pokemon_second_weapon %>/
          <%=@pokerank6.third_pokemon_third_weapon %>/
          <%=@pokerank6.third_pokemon_force_weapon %>
          </p><br>

          <%=link_to "このポケモンの記事を見にいく", article_path(@pokerank6.id), class:'small-link' %>


        </div>
      
      </div>

   <%end%>

 

    </div>

    <%#----------------------------------------------------------------%>



    <div class="new-article">
    
      
        <h1 class="blue-title">ー新着記事ー
        </h1>
        <div class="scroll">

          <% @articles.each do |article| %>
          
            <div class="new-article-link">
              <div class="new-article-info">
                投稿者：<span class="new-article-user"></span><%= link_to "#{article.user.name}", user_path(article.user_id), class:'new-article-user' %>
                 <div class="all-day"><%= article.created_at.strftime("%Y年%m月%d日")%></div>
              </div>
              <%= link_to "#{article.title}", article_path(article.id), class:'new-article-title' %>

              <div class="monster-choice">
                <%= render partial: "monster01", locals: { article: article } %>
                <%= render partial: "monster02", locals: { article: article } %>
                <%= render partial: "monster03", locals: { article: article } %>
                <%= render partial: "monster04", locals: { article: article } %>
                <%= render partial: "monster05", locals: { article: article } %>
                <%= render partial: "monster06", locals: { article: article } %>
              </div>

            
            </div>
        

          <%end%>  
          <div class="old-title-article">記事の一覧は<%= link_to "こちら", search_articles_path, class:'old-article-title' %></div>
        </div>  

    


    </div>

    

    <div class="old-article">
      <h1 class="blue-title">ー注目記事ー</h1>
        
        <div class="rank-field">
          
          <% @rank.each do |rank| %>

          <div class="rank-article"><span class="pika"></span>><%= link_to "#{rank.title}", article_path(rank.id), class:'rank-article-title' %></div>
          <%end%>
        </div>
        <div class="old-field">
          

          <div class="old-article-link">
            <div class="old-title-article">過去の記事一覧は<%= link_to "こちら", search_articles_path, class:'old-article-title' %></div>
          </div>
        </div>
    </div>

  </div>



</div> 

<footer>
      <div class="wrapper footer__wrapper ">
        <h1 class="footer-message">当サイトのイラスト画像等は全て使用許可を得ております</h1>
      </div>
</footer>

app/views/articles/success.html.erb
<%# 3秒後にリダイレクト %>
<meta http-equiv="refresh" content=" 3; url= /articles">
<%# 3秒後にリダイレクト %>

<div class="success-main-body">
  <div class="success-second-body">
    <div class="success-text-area">
     <p class="success-first-text"><span class="ball-image"></span>構築が投稿されました<span class="ball-image"></span></p>
     <p class="success-second-text">自動で構築トップページに戻ります</p>
     <p class="success-third-text">自動でリダイレクトしない場合は<%= link_to "こちら", articles_path, class: 'success-link'%>をクリック</p>
    </div>
  </div>

<div>

app/views/articles/success2.html.erb
<%# 3秒後にリダイレクト %>
<meta http-equiv="refresh" content=" 3; url= /articles">
<%# 3秒後にリダイレクト %>

<div class="success-main-body">
  <div class="success-second-body">
    <div class="success-text-area">
     <p class="success-first-text"><span class="ball-image"></span>構築が削除されました<span class="ball-image"></span></p>
     <p class="success-second-text">自動で構築トップページに戻ります</p>
     <p class="success-third-text">自動でリダイレクトしない場合は<%= link_to "こちら", articles_path, class: 'success-link'%>をクリック</p>
    </div>
  </div>

<div>