config/routes.rb
Rails.application.routes.draw do

  devise_for :users
  root to: "infomations#index"

  resources :users, only: [:show]

  resources :infomations, only: [:index,:create,:destroy] do
    collection do
     get 'fresh'
     get 'tool'
    end
  end

  resources :contacts, only: [:new,:create,:show,:index] do
    collection do
      get 'success'
     end
   end

  resources :articles do
    resources :comments, only: [:create,:destroy]

    collection do
      get 'success'
      get 'success2'
      get 'search'
      get 'all'
     end
   end


   resources :characters, only: [:index] do
    collection do
      get 'n0100'
      get 'n0200'
      get 'n0300'
      get 'character'
      
     end
   end


end

app/models/infomation.rb
class Infomation < ApplicationRecord
  belongs_to :user

  with_options presence: true do
    validates :text
  end
end

app/controllers/infomations_controller.rb
class InfomationsController < ApplicationController
  def index
    @infomations = Infomation.all.order(created_at: 'DESC').limit(20)
    @infomation = Infomation.new
  end

  def create
    @infomation = Infomation.new(infomation_params)
    if @infomation.save
      redirect_to root_path
    else
      render :index
    end
  end

  def destroy
    infomation = Infomation.find(params[:id])
    infomation.destroy
    redirect_to root_path
  end

  private

  def infomation_params
    params.require(:infomation).permit(:text).merge(user_id: current_user.id)
  end
end

app/helpers/infomations_helper.rb
module InfomationsHelper
end

app/views/infomations/_calendar.html.erb
<div class="calendar-wrapper">
  <h2 class="calendar-title">カレンダー</h2>
    <div id="next-prev-button">
        <span id="header"></span>
    </div>

    <div id="calendar"></div>
</div>

app/views/infomations/fresh.html.erb
<div class="fresh-body">

  <div class="fresh-main-body">
    <div class="fresh-second-body">
      <div class="first-field">
        <h2 class="fresh-title">POKEbrary</h2>
        <p class="intrduce">「POKEbrary」はポケットモンスターのゲームの対戦におけるパーティ構築の共有サイトです。<br>
            多くのプレイヤーのみなさんが投稿した構築記事を見ることができます。<br>
            TOPページ左の「構築記事」をクリックしていただくことで記事の閲覧ページへ進みます。<br>
            構築記事のページでは記事の閲覧ができ、構築TOPページには新着記事、注目記事、ポケモン使用率のランキングがあります。<br>
            また、ページ右上の「記事を検索する」ボタンから記事の検索ページへ進むことができます。検索ページでは、調べたいポケモンの
            名前を入れて検索していただくことで、そのポケモンが含まれている構築の記事の一覧を表示します。<br>
            注目記事の項目下部、「過去の記事一覧はこちら」のリンクから過去全ての記事を表示することができます。<br>
            構築記事のページでは、お持ちのユーザーでログインしていただくことで、構築記事へのコメント、構築記事の新規投稿を行うことができます。
            (※ユーザー登録は必須ではありません)<br><br>
            ・すでにユーザーをお持ちの方　→　<%= link_to 'ログイン', new_user_session_path , class:'fresh-login'%><br>
            ・すでにユーザーをお持ちの方　→　<%= link_to '新規登録', new_user_registration_path , class:'fresh-login'%>
            <br><br>
            メインTOPページ2番目の「ポケモン情報」には各ポケモンの詳細情報が記載されています。<br>
            メインTOPページ4番目の「お問い合わせ」では、当サイトに関する質問や要望、その他不具合の報告などを行うことができます。<br>
            注意事項をご確認のうえご利用ください。<br><br><br>
            ポケモントレーナーのみなさまのお力になれますと幸いです。



      </div>  
    </div>
  </div>

</div>

app/views/infomations/index.html.erb
<%= render "layouts/header"%>

<div class="center">
<div class="index-main">
<div class="infomation-body">
 <div class="title-index">
    <div class="site-title-index">
        <span class="myu-logo"></span><h1 class="site-title-top">POKEbrary TOPページ</h1>
    </div>
    <div class="battle-tool">
      <span class="zacian-logo"></span>
      <span class="tool-btn"><%= link_to "POKEbrary 対戦用ツール(タイマー・メモ)", tool_infomations_path, class: 'tool-btn' %>
      </span>
    </div>

  </div>



  <div class="infomation-second-body">
    <div class="select">
      <div class="selecter">
        <div class="clock">
          <span class="clock-font" id ="date" class="date"></span>
          <span class="clock-font" id ="clock" class="time"></span>
        </div>  
          
        <div class="select-div">
          <ul class="select-ul">
              <li class="select-li " id="select-list-1">
                <%= link_to "", articles_path, class: 'btn select-list-1' %>
              </li>
              <li class="select-li" id="select-list-2">
                <%= link_to "", characters_path, class: 'btn select-list-2' %>
              </li>
              <li class="select-li" id="select-list-3">
                <%= link_to "", fresh_infomations_path, class: 'btn select-list-3' %>
              </li>
              <li class="select-li" id="select-list-4">
                <%= link_to "", new_contact_path, class: 'btn select-list-4' %>
              </li>
          </ul>
        </div>

        <div class="select-monster">
             <div class="first-monster" id="first-monster">
             </div>
              <div class="first-message-box" id="first-message-box">
                <p class="first-message">4つのメニューから選んでね!<br>
                記事を投稿するにはログインが必要だよ〜<br>
                右上のボタンからログインしてね
                </p>
            </div>
         </div>   

         <div class="select-monster">
             <div class="second-monster" id="second-monster">
             </div>
             <div class="second-message-box" id="second-message-box">
              <p class="second-message">構築記事はこちら<br>
              ログインしていると記事の投稿ができるよ!<br>
              いろんなパーティを見てみよう!
              </p>
            </div>
         </div>   

         <div class="select-monster">
             <div class="third-monster" id="third-monster">
             </div>
             <div class="third-message-box" id="third-message-box">
              <p class="third-message">ポケモンの情報が載ってるよ!<br>
              情報を見ながら強い構築をつくっていこう!<br>
              (当サイトではトップ100のポケモンのみ)
              </p>
            </div>
         </div>   

         <div class="select-monster">
             <div class="force-monster" id="force-monster">
             </div>
             <div class="force-message-box" id="force-message-box">
              <p class="force-message">はじめての方は一回読んでみてね!<br>
              このサイトでできることが書いてあるよ<br>
              新規登録もここからできるよ!
              </p>
            </div>
         </div>   

         <div class="select-monster">
             <div class="fifth-monster" id="fifth-monster">
             </div>
             <div class="fifth-message-box" id="fifth-message-box">
              <p class="fifth-message">お問い合わせはこちらから!<br>
              注意事項をしっかり読んでから送ってね<br>
              ご意見やご要望も!
              </p>
            </div>
         </div>   
        </div>
        <div class="select-second">
          <div class="right-intr">
            <div class="right-intr-body">
              <div class="right-intr-text">｢POKEbrary｣はポケモン対戦に関する情報共有サイトです。
                    新商品や新ポケモンに関する情報も発信しております。
                    ポケモン攻略のツールとしてご活用ください。
              </div> 
              <div class="sns-area">
                <a href="https://twitter.com/mhV4b7Q4f32EPxL" class="twitter-logo"></a>
                <a href="#" class="youtube-logo"></a>
                <a href="#" class="facebook-logo"></a>
                <a href="#" class="insta-logo"></a>
              <div>
            </div>
            </div>  
          </div>
          
          <div class="select-search">
            <%= form_with(url: search_articles_path, local: true, method: :get, class: "search-index") do |form| %>
            <%= form.text_field :keyword, placeholder: "ポケモン名で検索", class: "search-text" %>
            <%= form.submit "検索", class: "select-search-btn" %>
            <% end %>
          </div>
          <div>
          <%= render partial: "calendar" %>

          </div>
        
        
        </div > 
      </div>

    </div> 

  </div>



</div>

<div class="infomation-third-body">

  <div class="notice">


    <div class="notice-body">
      
      <h1 class="notice-title">お 知 ら せ</h1>


      <%# お知らせ一覧%>
      <div class="info-scroll">
      <% @infomations.each do |info|%>
      <% wd = ["日", "月", "火", "水", "木", "金", "土"]%>
        <div class="notice-area">
          <div class="notice-day">
          <%= info.created_at.strftime("%Y年%m月%d日(#{wd[info.created_at.wday]})")%>
          </div>
          <div class="notice-text">
          <%= info.text%>
          </div>
           <% if user_signed_in? %>
          <p class="modal-open-delete" id="modal-open-delete">削除する</p>
          <%= link_to "削除する", infomation_path(info.id), method: :DELETE, id: 'notice-delete'%>
          <%end%>

          <%# モーダルウィンドウ 削除 %>
            <div id="modal-delete" class="info-delete-form">
              <div class="info-delete-text">
                <div class="delete-text-field">
                  <%= info.text %>
                </div>
              </div>
              <div class="text-button" id="text-submit">
                <p class="info-delete-question">こちらの投稿を削除しますか?</p>
                <button id="text-submit" class="info-delete-button">削除する</button>
              </div>    
            </div>
          <%# モーダルウィンドウ 削除 %>

        </div>
      <% end %>  
      </div>
      <%# お知らせ一覧%>

      
    </div>
    <% if user_signed_in? %>
    <div class="info-new" >
      <button class="info-new-btn" id="modal-open-new" >お知らせ追加</button>
    </div>
    <%end%>



  </div>

  <div class="tweet">
    <div class="tweet-intr">Twitter</div>
    <a class="twitter-timeline" href="https://twitter.com/mhV4b7Q4f32EPxL?ref_src=twsrc%5Etfw" width="400px" height="600px"></a> 
    <script async src="https://platform.twitter.com/widgets.js" charset="utf-8"></script>
  </div>

</div>







<footer>
      <div class="wrapper footer__wrapper ">
        <h1 class="footer-message">当サイトのイラスト画像等は全て使用許可を得ております</h1>
      </div>
</footer>





<%# モーダルウィンドウ new %>
<div id="modal-new">
  <%= form_with model: @infomation, class: 'form', local: true do |f| %>
  
    <div class="info-text-form" id="info-text-form">
      <%= f.text_area :text, class: 'infomation-text-area', placeholder: '内容を入力してください' %>
    </div>
      
    <div class="text-button" id="text-button">
      <%= f.submit '投稿する', class: 'text-submit' %>
    </div>  
  <% end %>
</div>
  <%# モーダルウィンドウ new %>

app/views/infomations/tool.html.erb
<div class="tool">

  <div class="timer-field">
    <h1 class="tool-title">対戦用ツール</h1>
    <form class="time-form" name="timer">
      <div class="timer-font">
      <input class="timer-text" type="text" value="20"><span class="timer-sub">分</span>
      <input class="timer-text" type="text" value="00"><span class="timer-sub">秒</span><br>
      </div>

      <div class="timer-button">
      <input class="timer-btn" type="button" value="スタート" onclick="cntStart()">
      <input class="timer-btn" type="button" value="ストップ" onclick="cntStop()">
      </div>
    </form>

    <div class="party-field">
      <div class="my-party">
        <h2 class="party-me">自分のパーティ</h2>
        <div class="my-field"><span class="tool-monster"></span>ポケモン①<input type="text"></div>
        <div class="my-field"><span class="tool-monster"></span>ポケモン②<input type="text"></div>
        <div class="my-field"><span class="tool-monster"></span>ポケモン③<input type="text"></div>
        <div class="my-field"><span class="tool-monster"></span>ポケモン④<input type="text"></div>
        <div class="my-field"><span class="tool-monster"></span>ポケモン⑤<input type="text"></div>
        <div class="my-field"><span class="tool-monster"></span>ポケモン⑥<input type="text"></div>
      </div>

      <div class="my-party">
        <h2 class="party-me">相手のパーティ</h2>
        <div class="my-field"><span class="tool-monster"></span>ポケモン①<input type="text"></div>
        <div class="my-field"><span class="tool-monster"></span>ポケモン②<input type="text"></div>
        <div class="my-field"><span class="tool-monster"></span>ポケモン③<input type="text"></div>
        <div class="my-field"><span class="tool-monster"></span>ポケモン④<input type="text"></div>
        <div class="my-field"><span class="tool-monster"></span>ポケモン⑤<input type="text"></div>
        <div class="my-field"><span class="tool-monster"></span>ポケモン⑥<input type="text"></div>
      </div>


    </div>

    <div class="memo-area">
    <h2 class="memo-title">メモ欄</h2>
      <textarea class="memo-field"></textarea>
    <div>





  </div>

</div>